### ISSUE TITLE
TypeError: p_test() missing 1 required positional argument: 'title'

### ISSUE THREAD

**Issue by wittrup** [picotech/picosdk-python-examples#1]
Hi

When running [pico_test.py](https://github.com/picotech/picosdk-python-examples/blob/master/python-picoscope/pico_test.py) I get the following errors/output:

```
C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_nosetest_runner.py" --path C:/Users/wittrup/Documents/GitHub/picosdk-python-examples/python-picoscope/pico_test.py
Testing started at 08.37 ...
Launching Nosetest with arguments C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_nosetest_runner.py C:/Users/wittrup/Documents/GitHub/picosdk-python-examples/python-picoscope/pico_test.py in C:\Users\wittrup\Documents\GitHub\picosdk-python-examples\python-picoscopeE
======================================================================
ERROR: pico_test.p_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: p_test() missing 1 required positional argument: 'title'
-------------------- >> begin captured stdout << ---------------------



--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
Exception: p_test() missing 1 required positional argument: 'title'





Process finished with exit code 1
```

How may I overcome this issue?

**Comment by hsmistry** [comment]
The pico_test.py script is just a test script but there aren't any unit tests associated. Please try the example scripts as documented in the README file.
