### ISSUE TITLE
pico_test.py ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by wittrup** [picotech/picosdk-python-examples#3]
### Setup

* Example filename: pico_test.py
* Version of Python: Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
* Pico Technology device model: PicoScope 2204A
* Driver name and version number: 2.3.0.6
* Operating system: Microsoft Windows [Version 10.0.15063]
* USB port type	(e.g. 2.0): 2.0

### Description

Running pico_test.py I get the following result:
```python
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Python27\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\wittrup\Documents\GitHub\picosdk-python-examples\python-picoscope\pico_test.py", line 14, in <module>
    import numpy as np
  File "C:\Python27\lib\site-packages\numpy\__init__.py", line 170, in <module>
    from . import add_newdocs
  File "C:\Python27\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Python27\lib\site-packages\numpy\lib\__init__.py", line 18, in <module>
    from .polynomial import *
  File "C:\Python27\lib\site-packages\numpy\lib\polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "C:\Python27\lib\site-packages\numpy\linalg\__init__.py", line 51, in <module>
    from .linalg import *
  File "C:\Python27\lib\site-packages\numpy\linalg\linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: DLL load failed: The specified module could not be found.
```

### Notes

From command line I may run:
```
c:\Python27\Scripts>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy.linalg import lapack_lite, _umath_linalg
>>>
```

So, how may I fix this error?
How may it be that pico_test.py fails to import stuff the console is able to import?

**Comment by hsmistry** [comment]
@wittrup, if this is a 64-bit Windows 10 OS, please ensure that the location of the ps2000.dll from the 32-bit PicoSDK on the Windows PATH environment variable is before the entry of the 64-bit PicoSDK (if it has been installed).

**Comment by wittrup** [comment]
`C:\Program Files (x86)\Pico Technology\SDK\lib\` on top in PATH environment variable.

Now there is a new error message:
```
Launching Nosetest with arguments C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_nosetest_runner.py C:/Users/wittrup/Documents/GitHub/picosdk-python-examples/python-picoscope/pico_test.py in C:\Users\wittrup\Documents\GitHub\picosdk-python-examples\python-picoscope
E
======================================================================
ERROR: pico_test.p_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: p_test() takes at least 1 argument (0 given)
-------------------- >> begin captured stdout << ---------------------



--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: p_test() takes at least 1 argument (0 given)
```

**Comment by hsmistry** [comment]
The pico_test.py script is just a test script but there aren't any unit tests associated. Please try the example scripts as documented in the (README)[README.md] file.

**Comment by hsmistry** [comment]
The pico_test.py script is just a test script but there aren't any unit tests associated. Please try the example scripts as documented in the README file.
